### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by caseylang** [hashicorp/rtmo-lesson-1#1]
I'm going through lesson 1 and am running into an issue. I'm using vagrant 1.7.4, have the plugin installed, and downloaded AppCatalyst directly from the provided webite. During `vagrant up` I'm receiving the following error:

``` console
# vagrant up
Bringing machine 'letschat' up with 'vmware_appcatalyst' provider...
==> letschat: Importing base box 'hashicorp/precise64'...
    letschat: Cloning VM, this might take a while...
==> letschat: Checking if box 'hashicorp/precise64' is up to date...
==> letschat: Waiting for machine to boot. This may take a few minutes...
    letschat: SSH address: 192.168.2.129:22
    letschat: SSH username: vagrant
    letschat: SSH auth method: private key
    letschat: Warning: Connection refused. Retrying...
    letschat: Warning: Connection refused. Retrying...
    letschat: Warning: Connection refused. Retrying...
    letschat: Warning: Connection refused. Retrying...
    letschat: Warning: Connection refused. Retrying...
    letschat: Warning: Connection refused. Retrying...
    letschat: Warning: Connection refused. Retrying...
Can't connect to AppCatalyst, please verify connectivity.
```

In another terminal, I have AppCatalyst running. 

``` console
# appcatalyst-daemon start
2015/09/03 13:13:16 WARNING: Can not find the config ($HOME/.appcatalyst.conf) file. Using Default values.
2015/09/03 13:13:16 DEFAULT_VM_PATH=/Users/langc/Documents/AppCatalyst
2015/09/03 13:13:16 DEFAULT_PARENT_VM_PATH=/opt/vmware/appcatalyst/photonvm/photon.vmx
2015/09/03 13:13:16 DEFAULT_LOG_PATH=/Users/langc/Library/Logs/VMware
2015/09/03 13:13:16 PORT=8080
2015/09/03 13:13:16 Swagger path: /opt/vmware/appcatalyst/bin/swagger
2015/09/03 13:13:16 appcatalyst daemon started.
2015-09-03T13:14:36.150| ServiceImpl_Opener: PID 16322
2015-09-03T13:16:55.185| ServiceImpl_Opener: PID 16447
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xa pc=0x4500030]

runtime stack:
runtime.gothrow(0x4387df0, 0x2a)
    /usr/local/go/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
    /usr/local/go/src/runtime/sigpanic_unix.go:14 +0x5e

goroutine 2723 [syscall, locked to thread]:
runtime.cgocall_errno(0x4001c70, 0xc208063a38, 0xc200000000)
    /usr/local/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc208063a18 sp=0xc2080639f0
gantry/govix._Cfunc_VixHost_Disconnect(0xc200100035)
    gantry/govix/_obj/_cgo_gotypes.go:177 +0x45 fp=0xc208063a38 sp=0xc208063a18
gantry/govix.(*Host).Disconnect(0xc208092470)
    /build/mts/release/bora-3024004/bora/apps/gantry/rest-daemon/src/gantry/govix/host.go:37 +0x4d fp=0xc208063a48 sp=0xc208063a38
main.get_ip_handler(0x4f2a1a8, 0xc20803e6e0, 0xc20801ec30)
    /build/mts/release/bora-3024004/bora/apps/gantry/rest-daemon/src/gantry/gantry.go:682 +0xb30 fp=0xc208063b78 sp=0xc208063a48
main.get_or_delete_vm_handler(0x4f2a1a8, 0xc20803e6e0, 0xc20801ec30)
    /build/mts/release/bora-3024004/bora/apps/gantry/rest-daemon/src/gantry/gantry.go:603 +0x1f2 fp=0xc208063c38 sp=0xc208063b78
net/http.HandlerFunc.ServeHTTP(0x43b39c0, 0x4f2a1a8, 0xc20803e6e0, 0xc20801ec30)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1265 +0x41 fp=0xc208063c58 sp=0xc208063c38
net/http.(*ServeMux).ServeHTTP(0xc20803c6c0, 0x4f2a1a8, 0xc20803e6e0, 0xc20801ec30)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1541 +0x17d fp=0xc208063cb0 sp=0xc208063c58
net/http.serverHandler.ServeHTTP(0xc20805a1e0, 0x4f2a1a8, 0xc20803e6e0, 0xc20801ec30)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1703 +0x19a fp=0xc208063d08 sp=0xc208063cb0
net/http.(*conn).serve(0xc20803e640)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1204 +0xb57 fp=0xc208063fd8 sp=0xc208063d08
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208063fe0 sp=0xc208063fd8
created by net/http.(*Server).Serve
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1751 +0x35e

goroutine 1 [IO wait]:
net.(*pollDesc).Wait(0xc2080101b0, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080101b0, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208010150, 0x0, 0x4f28b48, 0xc208092160)
    /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20804e028, 0x40c789e, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc20804e028, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc20805a1e0, 0x4f29ff0, 0xc20804e028, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc20805a1e0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0xc20802a9e4, 0x5, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1808 +0xba
main.main()
    /build/mts/release/bora-3024004/bora/apps/gantry/rest-daemon/src/gantry/gantry.go:1026 +0x105c

goroutine 4 [sleep]:
gantry/govix.cleanupVM(0xc208093030)
    /build/mts/release/bora-3024004/bora/apps/gantry/rest-daemon/src/gantry/govix/vm.go:595 +0x48

goroutine 17 [syscall, 5 minutes, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 2721 [IO wait]:
net.(*pollDesc).Wait(0xc208010300, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010300, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080102a0, 0xc20813a000, 0x1000, 0x1000, 0x0, 0x4f28b48, 0xc208092908)
    /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20804e048, 0xc20813a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc20803e408, 0xc20813a000, 0x1000, 0x1000, 0xc00000000000000, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc2080cc600, 0xc20813a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc20805a300)
    /build/toolchain/mac32/go-1.4.2/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc20805a300, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc20805a300, 0x0, 0x0, 0x0, 0xc207ff2f00, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc2080d00c0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc2080d00c0, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc20805a300, 0xc20801ea90, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc20803e3c0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc20803e3c0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1751 +0x35e

goroutine 2718 [IO wait]:
net.(*pollDesc).Wait(0xc2080105a0, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080105a0, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010540, 0xc208078000, 0x1000, 0x1000, 0x0, 0x4f28b48, 0xc208092118)
    /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20804e068, 0xc208078000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc20803e548, 0xc208078000, 0x1000, 0x1000, 0xc2080cc340, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc2080cc8e0, 0xc208078000, 0x1000, 0x1000, 0x4f2a2a8, 0x0, 0x0)
    /usr/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc20805a120)
    /build/toolchain/mac32/go-1.4.2/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc20805a120, 0x405dd0a, 0x0, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc20805a120, 0x0, 0x0, 0x0, 0xc2080d0600, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc2080d0660, 0x0, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc2080d0660, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc20805a120, 0xc20801ef70, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc20803e500, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc20803e500)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1751 +0x35e

goroutine 2722 [IO wait]:
net.(*pollDesc).Wait(0xc208010290, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010290, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010230, 0xc208084000, 0x1000, 0x1000, 0x0, 0x4f28b48, 0xc208092088)
    /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20804e040, 0xc208084000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc20803eb88, 0xc208084000, 0x1000, 0x1000, 0xc2080cdd80, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc2080cca40, 0xc208084000, 0x1000, 0x1000, 0x4f2a2a8, 0x0, 0x0)
    /usr/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc20805a2a0)
    /build/toolchain/mac32/go-1.4.2/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc20805a2a0, 0x405dd0a, 0x0, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc20805a2a0, 0x0, 0x0, 0x0, 0xc2080d0c00, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc2080d0690, 0x0, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc2080d0690, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc20805a2a0, 0xc20801eb60, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc20803eb40, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc20803eb40)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1751 +0x35e

goroutine 2720 [IO wait]:
net.(*pollDesc).Wait(0xc208010760, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010760, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010700, 0xc20807a000, 0x1000, 0x1000, 0x0, 0x4f28b48, 0xc208092180)
    /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20804e018, 0xc20807a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc20803eae8, 0xc20807a000, 0x1000, 0x1000, 0xc2080cc540, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc2080cc020, 0xc20807a000, 0x1000, 0x1000, 0x4f2a2a8, 0x0, 0x0)
    /usr/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc20805a240)
    /build/toolchain/mac32/go-1.4.2/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc20805a240, 0x405dd0a, 0x0, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc20805a240, 0x0, 0x0, 0x0, 0xc2080d0200, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc2080d0060, 0x0, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc2080d0060, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc20805a240, 0xc20801e820, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc20803eaa0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc20803eaa0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1751 +0x35e

goroutine 1114 [IO wait, 1 minutes]:
net.(*pollDesc).Wait(0xc208010b50, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010b50, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010af0, 0xc20807c000, 0x1000, 0x1000, 0x0, 0x4f28b48, 0xc208092cd8)
    /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20804e0f8, 0xc20807c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc20803f088, 0xc20807c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc2080cd2c0, 0xc20807c000, 0x1000, 0x1000, 0x1, 0x0, 0x0)
    /usr/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc20805a480)
    /build/toolchain/mac32/go-1.4.2/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc20805a480, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc20805a480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc2080d13b0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc2080d13b0, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc20805a480, 0xc20801fad0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc20803f040, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc20803f040)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1751 +0x35e

goroutine 1118 [IO wait, 1 minutes]:
net.(*pollDesc).Wait(0xc208010220, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010220, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080101c0, 0xc2080a2000, 0x1000, 0x1000, 0x0, 0x4f28b48, 0xc208092008)
    /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20804e030, 0xc2080a2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc20803e228, 0xc2080a2000, 0x1000, 0x1000, 0xc00000000000000, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc20809e0e0, 0xc2080a2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc20805a180)
    /build/toolchain/mac32/go-1.4.2/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc20805a180, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc20805a180, 0x0, 0x0, 0x0, 0xc207ff2f00, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc2080d0180, 0x0, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc2080d0180, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc20805a180, 0xc20801e8f0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc20803e1e0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc20803e1e0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1751 +0x35e

goroutine 2719 [IO wait]:
net.(*pollDesc).Wait(0xc2080106f0, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080106f0, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010690, 0xc208138000, 0x1000, 0x1000, 0x0, 0x4f28b48, 0xc208092008)
    /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20804e080, 0xc208138000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc20803e908, 0xc208138000, 0x1000, 0x1000, 0xc00000000000000, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc2080cc420, 0xc208138000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc20805a4e0)
    /build/toolchain/mac32/go-1.4.2/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc20805a4e0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc20805a4e0, 0x0, 0x0, 0x0, 0xc207ff2f00, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc2080d0000, 0x0, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc2080d0000, 0x0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc20805a4e0, 0xc20801e4e0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc20803e8c0, 0x0, 0x0, 0x0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc20803e8c0)
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
    /build/toolchain/mac32/go-1.4.2/src/net/http/server.go:1751 +0x35e
```

Any suggestions? If I've left out any necessary information please let me know and I'll provide it.

**Comment by frapposelli** [comment]
Hi @caseylang, seems like the AppCatalyst REST Daemon crashed during an operation, I'm sending this to the AppCatalyst team internally so they can take a look, in the meantime, just restarting the `appcatalyst-daemon` process should get you back in business.
